dist: bionic
language: python
python:
- '3.7'
env:
  global:
  - secure: T3rTOQOLkdK0JBpX1QmcCT+PRDgo1FAZurlDTptEFb8r+9K9ab97sBIWi9GmRms9m699ButVeP6Md536DlQ2T+DpjpV1iJW3RKEnKzzJsvl8LjJXyYD7BZnP+p+8AR3y7aPJF8Vw2cUa15wKO0oWUAikjTmbO4QaBv4GESxTNtIQnRe7UX1g+IHfAXoljzPqj03WfsYT4wykt6nB/+wf/kpBW6uh4Y36yscxLZ7v6O2Gphyw/t9dJW5niMDptm0jFk80D41JXwrn3J9rKx9jzEQerqbw0toX6onZvd+S/FCUf0YV8lVKcvcOr8OnwYjsguQ2CxeM1zQEZ07SOa2dJjTxyk8MyyZqWHf8Gge2eDu4BTY+MdfQChPfpLI8ubtKipp2lN04MdQN0r+0qEiBU7z5aVOr7wH9CYLPvf8zzq/yEblhDyLnew9i6wO1aMZ8cJ9vo5J76ohDJp8sNLk6XXtuMGdXVsLPdkA8iseyRi16YbsEkYLzflEe3TKPhqzlF6IZGN76yNn2fWs0iqbrE1Rod20NioafiRSPYYgsDqzX/3iugx2KiETpHWpftmaAqBCTiJgQiCBUEwGlHDCRlmR48ovch8j9ZpF+V5HI2ienCQtzevPhWBvuaBupreWeKgI2YYDUXupgCTWEKsa2AvDv9T/0PvvDwgUmh6c9ews=
  - secure: FEDuEiQl4BK6Y9KJqqPr9/6/1ieundnmFX/jdm5m4SCQMyrEKuU3h4/1dkb9l0KRRXHPfmjPgbUSNcDitjbV6D4+bS6oEWMvJ5ZvFCsC+moaha67taim3OJKd7O2XVPj4Wryitl5hQobAVgOtKHozx77cL0xayr2t/J4e6q49cKsIZ4DkOs+Q8Z9Jwjc/Sw4ceXwmqHfXqb3wAotO4XfOS5uO1v7KluAw0BzYpTfa1ytxVXwIkxYZfFUO/1s92ZtufD7KqSgFx4EkJGHsve53pKyQb69XJaTL+5eyjAb3j05lxKYJSb0IyDZYiD3K2GS+BBMoId2gjYxJTsGG2fojwOaApvDrP3CE9ZpX20Kqz0AGhsurJFGaJLM81P3U+JmZuElgBhl82wUK5mk47+yIFn4s+RilRydsKwuM5Kd7ixrBsKqW+nE4VKWI+5wnkhE0fjZ7bqE5BxE1ATIM3sENylA+C0vjOTjplJpy3jtZ3e9Z76MdGEnlHsmEe4jPuadWR/ssj2D3ceEqeIu+07G6bOJF7opPIZRTN325rsQJm8p3HR1+HOZVhGwqErsXcj4cDCY5/acAzPio8hD3QDDqFyEdfU/iVblNXBZnr/d/1NskhMPkracw9akf6x4i1YpQZpdswJ/tm/I87phSVeRILOxIO98QYa3ajPJhoBwdUA=
install:
- pip3 install poetry
- poetry install
script:
- poetry run pytest
