---
- project:
    merge-mode: squash-merge
    templates:
      - publish-to-pypi
    check:
      jobs:
        - tox-py37
        - tox-py38
        - tox-linters:
            vars:
              python_version: 3.7
    gate:
      jobs:
        - tox-py37
        - tox-py38
        - tox-linters:
            vars:
              python_version: 3.7
